CREATE TABLE filme(
	codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	titulo VARCHAR(125) NOT NULL UNIQUE,
    descricao VARCHAR(255) NOT NULL,
    duracao TIME(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
